name: Deploy Lambda Function

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Zip Lambda function
      run: |
        mkdir deployment_package
        cp -r app lambda_function.py requirements.txt deployment_package/
        cd deployment_package
        zip -r ../lambda.zip .
        cd ..

    - name: Deploy Lambda to AWS
      uses: aws-actions/aws-lambda-deploy-action@v1
      with:
        function-name: 'job-historico-2'  # Substitua pelo nome da sua Lambda
        zip-file: 'lambda.zip'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
