name: Deploy Lambda Function with Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Terraform
        run: |
          wget https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip || { echo "Failed to download Terraform"; exit 1; }
          sudo apt-get install unzip -y || { echo "Failed to install unzip"; exit 1; }
          unzip terraform_1.6.0_linux_amd64.zip || { echo "Failed to unzip Terraform"; exit 1; }
          sudo mv terraform /usr/local/bin/ || { echo "Failed to move Terraform binary"; exit 1; }

      - name: Set up AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV

      - name: Run terraform fmt to fix formatting
        run: terraform fmt

      - name: Initialize Terraform
        run: terraform init

      - name: Format and Validate Terraform
        run: |
          terraform fmt -check
          terraform validate

      - name: Create Lambda ZIP
        run: |
          zip -r lambda.zip .

      - name: Plan Terraform Deployment
        run: terraform plan -out=tfplan

      - name: Apply Terraform Deployment
        run: terraform apply -auto-approve tfplan
